import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";

 

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins", // create a CSS variable
  weight: ["400", "500", "600", "700"], // optional, choose the weights you need
});

export const metadata: Metadata = {
  title: "Magpieo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
